apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: portainer-demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost 
    http:
      paths:
        - path: /
          backend:
            serviceName: portainer-demo
            servicePort: 30080
