apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-demo
  labels:
    app: portainer-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: portainer-demo
  template:
    metadata:
      labels:
        app: portainer-demo
    spec:
      containers:
        - name: nginx-new
          image: nginx:1.21
          ports:
          - containerPort: 80
          imagePullPolicy: Always
